=== SviatoslavDusko/ta_lab_java/src/main/java/com/epam/lab/hw_15_json/task1_2/file-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "operator_name": {
      "type": "string"
    },
    "payroll": {
      "type": "string"
    },
    "call_prices": {
      "type": "object",
      "properties": {
        "on_network": {
          "type": "string"
        },
        "out_of_network": {
          "type": "string"
        },
        "stationary": {
          "type": "string"
        }
      },
      "required": [
        "on_network",
        "out_of_network",
        "stationary"
      ]
    },
    "sms_prices": {
      "type": "string"
    },
    "parameters": {
      "type": "object",
      "properties": {
        "fav_number": {
          "type": "string"
        },
        "tariffing": {
          "type": "string"
        },
        "connection_cost": {
          "type": "string"
        }
      },
      "required": [
        "fav_number",
        "tariffing",
        "connection_cost"
      ]
    }
  },
  "required": [
    "name",
    "operator_name",
    "payroll",
    "call_prices",
    "sms_prices",
    "parameters"
  ]
}

=== SviatoslavDusko/ta_lab_java/src/main/java/com/epam/lab/hw_15_json/task1_2/file.json
{
  "name": "Internet ta rozmovy",
  "operator_name": "Kyivstar",
  "payroll": "2000",
  "call_prices": {
    "on_network": "0",
    "out_of_network": "100",
    "stationary": "800"
  },
  "sms_prices": "600",
  "parameters": {
    "fav_number": "380985658553",
    "tariffing": "60",
    "connection_cost": "6000"
  }
}
