=== SviatoslavDusko/ta_lab_java/src/main/java/com/epam/lab/hw_14_xml/task1_2/file.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="tariffs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="operator_name" type="xsd:string"/>
                <xsd:element name="payroll" type="xsd:nonNegativeInteger"/>
                <xsd:element name="call_prices" type="call_prices"/>
                <xsd:element name="sms_prices" type="xsd:nonNegativeInteger"/>
                <xsd:element name="parameters" type="parameters"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="call_prices">
        <xsd:sequence>
            <xsd:element name="on_network" type="xsd:nonNegativeInteger"/>
            <xsd:element name="out_of_network" type="xsd:nonNegativeInteger"/>
            <xsd:element name="stationary" type="xsd:nonNegativeInteger"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="parameters">
        <xsd:sequence>
            <xsd:element name="favorite_number" type="xsd:positiveInteger"/>
            <xsd:element name="tariffing" type="xsd:positiveInteger"/>
            <xsd:element name="connection_cost" type="xsd:nonNegativeInteger"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== SviatoslavDusko/ta_lab_java/src/main/java/com/epam/lab/hw_14_xml/task1_2/file.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file.xsd">
    <name>Internet plus</name>
    <operator_name>Kyivstar</operator_name>
    <payroll>1000</payroll>
    <call_prices>
        <on_network>10</on_network>
        <out_of_network>50</out_of_network>
        <stationary>1000</stationary>
    </call_prices>
    <sms_prices>400</sms_prices>
    <parameters>
        <favorite_number>380985658553</favorite_number>
        <tariffing>60</tariffing>
        <connection_cost>9000</connection_cost>
    </parameters>
</tariffs>
